name: CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false # Disable submodule checkout if not needed

      # Step to remove bad submodule references
      - name: Remove bad submodule references
        run: |
          # Check if submodule exists and clean it up if necessary
          git submodule deinit -f vue-material-kit || echo "No submodule to deinit"
          git rm --cached vue-material-kit || echo "No submodule to remove"
          git clean -ffdx
          git reset --hard HEAD

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies and run tests
        run: |
          npm install
          # Conditionally run tests if the test script exists
          if npm run | grep -q "test"; then
            echo "Test script found, running tests..."
            npm test
          else
            echo "No test script found, skipping tests."
          fi

  build-and-push:
    if: github.repository_owner == 'omilabs'
    needs: tests
    runs-on: self-hosted
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false # Prevent submodule checkout if unnecessary

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build vue-material-kit Docker image
        run: docker build -t omisam/vue-material-kit:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image
        run: docker push omisam/vue-material-kit:latest

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Snyk Security Scan for Docker Image
        run: snyk container test omisam/vue-material-kit:latest --file=./Dockerfile || echo "Snyk found vulnerabilities"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
