apiVersion: v1
kind: Service
metadata:
  name: vue-material-kit-service
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    app: vue-material-kit
